app = "mybot-telegram"

[build]
  image = "python:3.12-slim"

[env]
  PYTHONUNBUFFERED = "true"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80
